### PR TITLE
Fixes the new line on save issue

### PR DESCRIPTION
**Pull request by BharatKalluri**
Hey @jevakallio ,

Thanks for all your work! love the extension/ideas.

It looks like on every save, the refs are created on a new line. What is happening is that [we are inserting a new line for every `create` of ref and in the next save we insert the refs in doc line count + 1 which inturn spawns another new line](https://github.com/foambubble/foam-vscode/blob/965fca3bdd840ba08db6846e20ad605b5b51d9ea/src/extension.ts#L83)

Now we have two functions, one is called `clearReferenceListFromFile` and another called `UpdateReferenceList`. Update reference list will always do clear first and then create. This also makes it easier to write tests in the future.  (I think `UpdateReferenceList` should be called `UpsertReferenceList`, but this is mongo vocabulary and not everyone might know it :smile: , if it makes sense for you I will rename it).

Have a look and let me know what you think. This is my first time working on a vs code extension, let me know if there is anything to improve :sweat_smile:

### CODE REVIEW

**Comment by Georift** [comment]
So I gave this a try on my Windows machine, looks to have fixed the new line issue. However I'm now no longer seeing the "Link References (up to date)` line which I do see when running on master.

Like @BharatKalluri, I haven't worked with extensions before so this might be self inflicted. To test is it just "Run Extension" in the repo?

**Comment by Georift** [comment]
Despite this references seem to be updating on pages that contain links and I'm seeing "Link references (out of date)" in these files.

**Comment by jevakallio** [comment]
@Georift thanks for testing! The CodeLens "(up to date)" should work in the new VSCode instance that's launched when you run/debug extension from VSCode.

I'll need to test this myself on a few edge cases before I can merge this.

This is why you should never launch anything without automated test coverage... 🤬

**Comment by jevakallio** [comment]
> Despite this references seem to be updating on pages that contain links and I'm seeing "Link references (out of date)" in these files.

This is probably because the CodeLensProvider (see bottom of extension.ts) generates a new version of the reference list and compares it to the existing one. Even a small difference (e.g. newline) will cause this to show "out of date".

**Comment by Georift** [comment]
> I'll need to test this myself on a few edge cases before I can merge this.

Very fair, I'm still getting a sense for how foam works, let alone subtlies.

> This is probably because the CodeLensProvider (see bottom of extension.ts) generates a new version of the reference list and compares it to the existing one. Even a small difference (e.g. newline) will cause this to show "out of date".

Oh right, interestingly I've only ever seen the up to date when the file doesn't have any references. Even after I add a new reference, save and see if add a new line it shows out of date. Must be some windows quirk. GL!

**Comment by jevakallio** [comment]
@Georift appreciate you testing it, it's actually very helpful!

**Comment by jevakallio** [comment]
@BharatKalluri thanks for this PR! I tested it, but the behaviour was not quite as expected. As @Georift had found, the CodeLens "up to date" was never to date, and that's because the line numbers were still being incorrectly calculated. 

Additionally, your approach assumed that the reference list would always be at the end of the file, but I or other plugins may in the future want to include additional write-only metadata in the file, so it's important this plugin only replaces the range it needs to.

Instead of adjusting the line numbers, I went a slightly different direction which you can see here:
https://github.com/foambubble/foam-vscode/pull/13

This is released as [v0.1.5](https://github.com/foambubble/foam-vscode/releases/tag/v0.1.5). Feel free to upgrade from the extension marketplace and test the issue is indeed fixed in your environments? I tested it with both EOL settings, plus with and without other auto-formatters like Prettier, and it appears to work.

**Pull request closed without merging**
